"""Add logo_url to job

Revision ID: b319088e586e
Revises: bf5acb5ff4ef
Create Date: 2026-07-02 14:57:14.271049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b319088e586e'
down_revision: Union[str, Sequence[str], None] = 'bf5acb5ff4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'logo_url')
    # ### end Alembic commands ###
