"""Add auto_tailor_resume to user_configs

Revision ID: bf5acb5ff4ef
Revises: eff85a243f33
Create Date: 2026-07-01 22:35:59.606267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bf5acb5ff4ef"
down_revision: Union[str, Sequence[str], None] = "eff85a243f33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_configs",
        sa.Column(
            "auto_tailor_resume",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_configs", "auto_tailor_resume")
    # ### end Alembic commands ###
